### ISSUE TITLE
Documentation typo in Creating a detached editor

### ISSUE THREAD

**Issue by ysct** [ckeditor/ckeditor5-editor-decoupled#37]
In the documentation page
https://github.com/ckeditor/ckeditor5-editor-decoupled/blob/5d0c0d771dc93b301f0b1d96c7b49ca6723ec711/src/decouplededitor.js#L155

I believe Line 155 should have been 
`document.body.appendChild( editor.ui.view.editable.element );`
instead of 
`document.body.appendChild( editor.ui.element );`

Thank you.

**Comment by Reinmar** [comment]
Thanks for reporting!

**Comment by oleq** [comment]
I'd go with `editor.ui.getEditableElement()` since we have this API.

OTOH I noticed that `DecoupledEditorUI` does not implement `#element` (inherited `null` from `EditorUI`). Maybe we should simply implement `#element` instead? All other editors do that.

**Comment by Reinmar** [comment]
What would `DecoupledEditorUI#element` be? It was supposed to be the main editor element. `DecoupledEditor` doesn't have it because it consists of two separate elements at the moment. I'd rather keep it clean that you need to specifically choose what you want to do. When using this editor you need to know where to get the toolbar from anyway, so there's no way to use it without docs.

> I'd go with `editor.ui.getEditableElement()` since we have this API.

👍
